name: receita_front
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  intl: any
  meta: ^1.2.2

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_rating_bar: ^4.0.1
  comment_box: ^0.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  form_field_validator: ^1.0.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true